excluded:
- "**/*.pb.swift"

disabled_rules:
- switch_case_alignment
- trailing_whitespace
- identifier_name
- opening_brace # Has false positives in the code base

# Re-enable these rules later once more warnings are fixed
- nesting
- todo

line_length: 160
type_body_length: 300
function_parameter_count: 8
file_length: 500
function_body_length: 50 
