format_version = 2

[apps.DeltaClient]
category = 'public.app-category.games'
icon = 'AppIcon.icns'
identifier = 'dev.stackotter.delta-client'
product = 'DeltaClient'
version = 'v0.1.0-alpha.1'

[apps.DeltaClient.plist]
CFBundleShortVersionString = '$(VERSION), commit: $(COMMIT_HASH)'