name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Xcodes
        run: ls /Applications
      - name: Force Xcode 14.2
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Version
        run: swift --version
      - name: Download swift-bundler
        run: |
          curl -o swift-bundler -L https://github.com/stackotter/swift-bundler/releases/download/v2.0.4/swift-bundler
          chmod +x ./swift-bundler
          cp ./swift-bundler /usr/local/bin
      - name: Build
        run: |
          ./swift-bundler bundle -c release -o . -u
          plutil -insert MetalCaptureEnabled -bool YES DeltaClient.app/Contents/Info.plist
      - name: Zip .app
        run: zip -r DeltaClient.zip DeltaClient.app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: DeltaClient
          path: ./DeltaClient.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd Sources/Core
          swift build
