name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  swift-lint:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: |
          URL="https://github.com/realm/SwiftLint/releases/download/0.50.3/portable_swiftlint.zip"
          curl -LO "$URL"
          unzip portable_swiftlint -d ./swiftlint
          rm -rf portable_swiftlint.zip
          echo "Linting with swiftlint $(./swiftlint/swiftlint version)"
          ./swiftlint/swiftlint lint --reporter github-actions-logging
        shell: bash
