name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-11
    steps:
      - name: Checkout delta-client
        uses: actions/checkout@v2
      - name: Force Xcode 13.2
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app
      - name: Version
        run: swift --version
      - name: Test
        run: |
          cd Sources/Core
          swift test
